[package]
name = "pw1"
version = "0.1.0"
authors = ["Vlado Boza <bozavlado@gmail.com>"]

[dependencies]
ndarray = { version = "0.11.0", features = ["blas"] }
blas-src = { version = "0.1.2", default-features = false, features = ["intel-mkl"] }
rand = "0.5.0-pre.0"